sudo: required
services:
    - docker

before_install:
    - docker build -t kujjwal02/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true kujjwal02/react-test npm run test

after_sucess:
    - docker build -t kujjwal02/multi-client ./client
    - docker build -t kujjwal02/multi-nginx ./nginx
    - docker build -t kujjwal02/multi-server ./server
    - docker build -t kujjwal02/multi-worker ./worker
    # Login to docker CLI
    - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    # Push the image to docker hub
    - docker push kujjwal02/multi-client
    - docker push kujjwal02/multi-nginx
    - docker push kujjwal02/multi-server
    - docker push kujjwal02/multi-worker